### ISSUE TITLE
Code linting not updating realtime (Svelte for VS Code)

### ISSUE THREAD

**Issue by ShapeMess** [sveltejs/language-tools#1329]
**Describe the bug**
Svelte for VS Code extension v105.9.0 seems to have introduced a bug with JS/TS scripts which results in linting completely breaking. Errors and warnings are not being updated realtime nor on file save. After a few code changes hover tooltips are showing content for different lines in the document. Snippets and completion are not working properly and are suggesting content for source code that was originally loaded in specific line in the file.
Reloading the editor helps only until the code is edited, after which another reload is requred.

**To Reproduce**
1. Install version v105.9.0 of the extension.
2. Edit the source code, introduce some errors and check tooltips.

**Expected behavior**

**Screenshots**
Window object reference right after a reload:
![screen1](https://user-images.githubusercontent.com/80402817/148809660-149ac9bf-27a0-4942-9cf6-f191f705755c.png)
After changing the window reference to an invalid piece of code, there are no errors, warnings and hints still suggest this is a window object.
![screen2](https://user-images.githubusercontent.com/80402817/148810160-04c32b16-f426-4dad-b8f7-3f0a6c2a0510.png)
After a reload:
![screen3](https://user-images.githubusercontent.com/80402817/148811896-f94e8343-b389-4687-8faf-ce1e0d24a661.png)
Errors/warning basically sit in place(?) Which looks like linting is done only on initial load and then stops.
![screen4](https://user-images.githubusercontent.com/80402817/148813565-d2edfadf-d5e2-4ea9-8d4c-69eb277f1e36.png)

**System:**
 - OS: Windows 10 21H2 (build 19044.14.15)
 - IDE: VSCode 1.63
 - Plugin/Package: "Svelte for VSCode",
 - Node: v16.10.0

**Additional context**
Linting is only being done once per file and then requires an editor reload - This would suggest why errors "stay in place" after editing the source code.

<!-- Want to help us out? Read this to get started:
https://github.com/sveltejs/language-tools#development
--

>

**Comment by dummdidumm** [comment]
I can't reproduce this using Windows and the latest Svelte for VS Code extension. Does this only happen on the latest version for you, so if you install a previous version it works? Could you provide the complete code of the file where this occurs in a way that I can copy-paste it?

**Comment by ShapeMess** [comment]
This issue appears in every file I have tested in basically all my projects, using older VSCode versions doesnt help, I have even gone as far as to reinstalling the editor along with removig all of its files, the only case in which the issue disappears is when using the an older version of the extension. 

I can provide you with some source code later this day as I get back to my computer, but I'm not sure if that's gonna help this problem persists in every other file.

**Comment by dummdidumm** [comment]
So if an older version of the extension (_not_ an older version of VS Code) does not fix the issue, this sounds like it's unrelated to the extension, although I don't know why it suddenly appeared for you.

**Comment by ShapeMess** [comment]
Rolling back the extension ro a previous version does fix the issue. Sorry if I didn't make it clear.

**Comment by dummdidumm** [comment]
Ah I see, thanks. Could you
1. Add `"svelte.trace.server": "messages"` to your settings.json
2. restart vs code 
3. go to Ouput(in the terminal area)->Svelte
4. Reproduce the issue
5. paste the result of that output  in here?

**Comment by ShapeMess** [comment]
This is the entire output after restarting VS Code and reproducing the issue.
Haven't compiled the code or anything so this is everything that's happening right after the editor first loads the file and the code was slightly edited to reproduce the issue.

```
[Trace - 23:43:26] Sending request 'initialize - (0)'.
Initialize language server at  file:///c%3A/Users/Shape/Desktop/VSCode/CV
[Trace - 23:43:28] Received response 'initialize - (0)' in 1288ms.
[Trace - 23:43:28] Sending notification 'initialized'.
[Trace - 23:43:28] Sending notification 'workspace/didChangeConfiguration'.
[Trace - 23:43:28] Sending notification 'textDocument/didOpen'.
No svelte.config.js found. Using https://github.com/sveltejs/svelte-preprocess as fallback
Using svelte-preprocess v4.9.8 from c:\Users\Shape\Desktop\VSCode\CV\node_modules\svelte-preprocess
[Trace - 23:43:28] Sending request 'textDocument/codeAction - (1)'.
[Trace - 23:43:28] Sending request 'textDocument/documentColor - (2)'.
[Trace - 23:43:28] Sending request 'textDocument/linkedEditingRange - (3)'.
Initialize new ts service at  c:/Users/Shape/Desktop/VSCode/CV/tsconfig.json
Trying to load configs for c:/Users/Shape/Desktop/VSCode/CV
No svelte.config.js found. Using https://github.com/sveltejs/svelte-preprocess as fallback
Using svelte-preprocess v4.9.8 from c:\Users\Shape\Desktop\VSCode\CV\node_modules\svelte-preprocess
[Trace - 23:43:28] Sending notification '$/cancelRequest'.
[Trace - 23:43:28] Sending request 'textDocument/codeAction - (4)'.
[Trace - 23:43:28] Sending request 'textDocument/documentSymbol - (5)'.
SnapshotManager File Statistics:
Project files: 18
Svelte files: 10
From node_modules: 0
Total: 18
[Trace - 23:43:28] Received response 'textDocument/linkedEditingRange - (3)' in 198ms.
[Trace - 23:43:31] Sending notification 'textDocument/didChange'.
[Trace - 23:43:31] Sending notification '$/cancelRequest'.
[Trace - 23:43:31] Sending request 'textDocument/completion - (6)'.
[Trace - 23:43:31] Sending notification 'textDocument/didChange'.
[Trace - 23:43:31] Sending notification 'textDocument/didChange'.
[Trace - 23:43:31] Sending notification 'textDocument/didChange'.
[Trace - 23:43:31] Sending notification 'textDocument/didChange'.
[Trace - 23:43:32] Sending notification 'textDocument/didChange'.
[Trace - 23:43:32] Received response 'textDocument/codeAction - (1)' in 3876ms.
[Trace - 23:43:32] Received response 'textDocument/codeAction - (4)' in 3744ms.
[Trace - 23:43:32] Received response 'textDocument/documentColor - (2)' in 3879ms.
[Trace - 23:43:32] Received response 'textDocument/documentSymbol - (5)' in 3756ms.
Using Svelte v3.44.2 from c:\Users\Shape\Desktop\VSCode\CV\node_modules\svelte\compiler
[Trace - 23:43:32] Sending notification 'textDocument/didChange'.
[Trace - 23:43:32] Sending notification 'textDocument/didChange'.
[Trace - 23:43:32] Sending request 'textDocument/linkedEditingRange - (7)'.
[Trace - 23:43:32] Sending request 'textDocument/codeAction - (8)'.
[Trace - 23:43:32] Sending request 'textDocument/documentColor - (9)'.
Using Svelte v3.44.2 from c:\Users\Shape\Desktop\VSCode\CV\node_modules\svelte\compiler
[Trace - 23:43:33] Received notification 'textDocument/publishDiagnostics'.
[Trace - 23:43:33] Received response 'textDocument/completion - (6)' in 1477ms.
[Trace - 23:43:33] Received response 'textDocument/linkedEditingRange - (7)' in 862ms.
[Trace - 23:43:33] Received response 'textDocument/codeAction - (8)' in 848ms.
[Trace - 23:43:33] Sending request 'textDocument/codeAction - (10)'.
[Trace - 23:43:33] Received response 'textDocument/codeAction - (10)' in 4ms.
Using Svelte v3.44.2 from c:\Users\Shape\Desktop\VSCode\CV\node_modules\svelte\compiler
Using Svelte v3.44.2 from c:\Users\Shape\Desktop\VSCode\CV\node_modules\svelte\compiler
[Trace - 23:43:34] Received notification 'textDocument/publishDiagnostics'.
[Trace - 23:43:34] Received response 'textDocument/documentColor - (9)' in 1623ms.
[Trace - 23:43:34] Sending request 'textDocument/codeAction - (11)'.
[Trace - 23:43:34] Received response 'textDocument/codeAction - (11)' in 4ms.
[Trace - 23:43:37] Sending request 'textDocument/documentSymbol - (12)'.
[Trace - 23:43:38] Received response 'textDocument/documentSymbol - (12)' in 1020ms.
[Trace - 23:43:52] Sending request 'textDocument/hover - (13)'.
[Trace - 23:43:52] Received response 'textDocument/hover - (13)' in 18ms.
[Trace - 23:43:56] Sending request 'textDocument/hover - (14)'.
[Trace - 23:43:56] Received response 'textDocument/hover - (14)' in 60ms.

```

**Comment by ShapeMess** [comment]
I couldn't see any errors either. I'm starting to think it may be caused by some obscure configuration or conflicts stored deep in system directories I couldn't find?
The verbose logs are 75k lines long, here's a link to the file so I won't have to spam it here.
https://www.dropbox.com/s/eahcvpa56el1iop/logs-11.01.22.txt?dl=0

**Comment by dummdidumm** [comment]
This is really super strange. According to the log the diagnostics are published correctly, I see an error about "windowasd" not being defined at the end. So this is either the client side of the extension that is somehow buggy on your end, or VS Code itself trips up somewhere along the way. 
Maybe this is another hickup of VS Code when installing the extension (#1296 being another example of that). What if you install the extension through downloading it from [the website](https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode) and manually installing it?

**Comment by ShapeMess** [comment]
Installing the extension directly from a local file did the job. It's strange though, as if VS Code had tripped during the instalation process. But that wouldn't explain why reinstalling it a couple times haven't fixed the issue before. As far as I know installing an addon from within VS Code works similarly, first downloading the file and then extracting it, just ommitting the manual download process.

**Comment by ShapeMess** [comment]
Anyways, seems like it's something wrong with VS Code handling the installation process and possible errors...
I'll diagnose all this on my own since it's probably the editor. Thanks for help and all the time you wasted on something that turned out to be more of an issue of the editor itself. I'll keep you informed if the issuereappears in the future - maybe something got deprecated and so the extension failed to install?

**Comment by dummdidumm** [comment]
Thanks for confirming that this is not on our part! If you want, you could try to find out if there are files missing when you do the installation from the marketplace and not through the direct download by looking at the content of the vsix file (you can look into it with 7zip for example) and the content of the auto-installed version which should be somewhere in your user folder.

**Comment by mellson** [comment]
I have the same error in my setup. I'm using the arm64 version of vscode, v: 1.63.2 and v105.10.0 of the Svelte extension.
Like @ShapeMess if I introduce errors in a file they are not highlighted before a restart, or if I open tsconfig.json and save that file (that somehow triggers a change as well).

Installing the plugin from a file does not fix it for me. I still have to either restart the language server or touch the tsconfig file.

**Comment by dummdidumm** [comment]
Could you do these steps https://github.com/sveltejs/language-tools/issues/1329#issuecomment-1009374415 and paste the result?

**Comment by mellson** [comment]
@dummdidumm sure thing, will do that now. Just a thought, maybe this could be related to running on an arm mac. I'm having the problem on a M1 Mac and just tried to open this through GitPod (which I think is intel based) and using GitPod there's no problems.

**Comment by mellson** [comment]
the output is:

```
Initialize language server at  file:///Users/mellson/Git/playground/appbureauet-svelte
Initialize new ts service at  /Users/mellson/Git/playground/appbureauet-svelte/tsconfig.json
Trying to load configs for /Users/mellson/Git/playground/appbureauet-svelte
Loaded config at  /Users/mellson/Git/playground/appbureauet-svelte/svelte.config.js
SnapshotManager File Statistics:
Project files: 17
Svelte files: 8
From node_modules: 0
Total: 17
Using Svelte v3.46.2 from /Users/mellson/Git/playground/appbureauet-svelte/node_modules/.pnpm/svelte@3.46.2/node_modules/svelte/compiler
Using Svelte v3.46.2 from /Users/mellson/Git/playground/appbureauet-svelte/node_modules/.pnpm/svelte@3.46.2/node_modules/svelte/compiler
Using Prettier v2.5.1 from /Users/mellson/.vscode/extensions/svelte.svelte-vscode-105.10.0/node_modules/prettier
Using Prettier v2.5.1 from /Users/mellson/.vscode/extensions/svelte.svelte-vscode-105.10.0/node_modules/prettier
Using Svelte v3.46.2 from /Users/mellson/Git/playground/appbureauet-svelte/node_modules/.pnpm/svelte@3.46.2/node_modules/svelte/compiler
Using Svelte v3.46.2 from /Users/mellson/Git/playground/appbureauet-svelte/node_modules/.pnpm/svelte@3.46.2/node_modules/svelte/compiler
Using Prettier v2.5.1 from /Users/mellson/.vscode/extensions/svelte.svelte-vscode-105.10.0/node_modules/prettier
Using Prettier v2.5.1 from /Users/mellson/.vscode/extensions/svelte.svelte-vscode-105.10.0/node_modules/prettier
Using Svelte v3.46.2 from /Users/mellson/Git/playground/appbureauet-svelte/node_modules/.pnpm/svelte@3.46.2/node_modules/svelte/compiler
Using Svelte v3.46.2 from /Users/mellson/Git/playground/appbureauet-svelte/node_modules/.pnpm/svelte@3.46.2/node_modules/svelte/compiler
```

Nothing looks suspicious there to my eyes. Also when I touch the tsconfig file to make the linting work again nothing changes in the Svelte output window.

**Comment by mellson** [comment]
Update just tried the same project on an intel mac using vscode 1.63.2 (Universal) and v105.10.0 of the Svelte plugin and here there's no problems. And this mac is also running macOS v12.1 (21C52) - so I think this has something to do with vscode on arm macs 🤔

**Comment by mellson** [comment]
Think I found a work around, this seems to be a problem on a file-by-file basis. Once a file has this problem it seems stuck in this mode.

But I found after renaming the file the error goes away. So for now I can rename the file to something else, verify the problem has gone away, and then rename it back to the original name.

**Comment by ShapeMess** [comment]
Just to finish things off with what I found out since the last time I spoke here. I could not figure out what that issue was caused by for sure, but it's seems like it's something specifically with VSCode and/or configuration and not the extension itself, I tried out the insiders version and the issue wasn't showing up. Though I have settings synced between the two, so I don't think it has to do with anything that's easily configurable by the user and more with the underlying configuration.

**Comment by JoDo-dev** [comment]
I had a similar problem... in my case it was a simple Linting issue with Typescript:

Wrong:
```
// Object "createNewRef" is possibly 'undefined'.
createNewRef.focus();
```

easy Fix:
```
createNewRef?.focus();
```

However, every time I resolved such issues, I had to restart the Svelte language server to see that the issue was solved. The issues would not disappear without restarting the language server.

To be able to use linting in real-time, I had to switch versions.
The latest Version without this problem is currently: `v105.21.0`

**Comment by JoDo-dev** [comment]
Jup, I had this issue in `105.22.0` and `105.22.1`

**Comment by falco467** [comment]
I can confirm the problem on v105.22.1 - The extension is unsuable for me in this state, since linting breaks almost every 5 seconds and I have to restart the language server to get any intellisense working.

If I just downgrade to v105.21.0 via the VSCode Extension Option, the error is still there (even after restarting VS Code), but if I uninstall the extension and install v105.21.0 from VSIX the error is fixed.

**Comment by ShapeMess** [comment]
I will just add that switching to a respective VS Code Insiders version literally always fixed the issue for me. So far this has only happened to me in the regular version and I've been using regular/insiders interchangebly. Not sure what others have experienced in that context.

**Comment by jasonlyu123** [comment]
Can you check if the output channel logged any errors? It's near the integrated terminal. Chose "svelte" in the dropdown at the top right corner of it. Wondering if typescript 4.8 changes something causing an error. 

If there isn't, you might have to provide a reproduction. Otherwise, we can't do anything about it.

**Comment by ShapeMess** [comment]
@jasonlyu123 I don't currently have this issue. It appears and disappears every now and then. I just wanted to point out that insiders haven't given me any issues related to that topic, and that's for a few good months.

**Comment by falco467** [comment]
The log shows only the following error:
```
Using Svelte v3.48.0 from c:\Workspace\svelteTest\my-app\node_modules\svelte\compiler
Parsing c:/Workspace/svelteTest/my-app/src/Overview.svelte failed. No preprocess config found but lang tag exists. Skip 
showing error because they likely use other preprocessors.
```

**Comment by falco467** [comment]
Here is also the added log with tracing enabled. But this seems to be the only error:

```
Using Svelte v3.48.0 from c:\Workspace\svelteTest\my-app\node_modules\svelte\compiler
Using Svelte v3.48.0 from c:\Workspace\svelteTest\my-app\node_modules\svelte\compiler
Parsing c:/Workspace/svelteTest/my-app/src/Overview.svelte failed. No preprocess config found but lang tag exists. Skip showing error because they likely use other preprocessors.
[Trace - 13:52:43] Received notification 'textDocument/publishDiagnostics'.
[Trace - 13:52:43] Sending request 'textDocument/semanticTokens/full - (18)'.
[Trace - 13:52:44] Sending request 'textDocument/codeAction - (19)'.
[Trace - 13:52:44] Received response 'textDocument/codeAction - (19)' in 4ms.
[Trace - 13:52:44] Received response 'textDocument/semanticTokens/full - (18)' in 1019ms.
[Trace - 13:52:45] Sending notification 'textDocument/didChange'.
[Trace - 13:52:45] Sending notification 'textDocument/didChange'.
[Trace - 13:52:45] Sending notification 'textDocument/didChange'.
[Trace - 13:52:45] Sending request 'textDocument/codeAction - (20)'.
[Trace - 13:52:45] Received response 'textDocument/codeAction - (20)' in 33ms.
[Trace - 13:52:46] Sending request 'textDocument/documentColor - (21)'.
[Trace - 13:52:46] Sending request 'textDocument/codeAction - (22)'.
[Trace - 13:52:46] Received response 'textDocument/codeAction - (22)' in 3ms.
Using Svelte v3.48.0 from c:\Workspace\svelteTest\my-app\node_modules\svelte\compiler
Using Svelte v3.48.0 from c:\Workspace\svelteTest\my-app\node_modules\svelte\compiler
Parsing c:/Workspace/svelteTest/my-app/src/Overview.svelte failed. No preprocess config found but lang tag exists. Skip showing error because they likely use other preprocessors.
[Trace - 13:52:46] Received notification 'textDocument/publishDiagnostics'.
[Trace - 13:52:46] Sending request 'textDocument/codeAction - (23)'.
[Trace - 13:52:46] Received response 'textDocument/codeAction - (23)' in 2ms.
[Trace - 13:52:47] Sending request 'textDocument/semanticTokens/full - (24)'.
[Trace - 13:52:47] Received response 'textDocument/documentColor - (21)' in 1008ms.
[Trace - 13:52:47] Sending request 'textDocument/codeAction - (25)'.
[Trace - 13:52:47] Received response 'textDocument/codeAction - (25)' in 2ms.
[Trace - 13:52:47] Sending notification 'textDocument/didChange'.
[Trace - 13:52:48] Sending notification 'textDocument/didChange'.
[Trace - 13:52:48] Sending notification 'textDocument/didChange'.
[Trace - 13:52:48] Sending request 'textDocument/completion - (26)'.
[Trace - 13:52:48] Received response 'textDocument/completion - (26)' in 23ms.
[Trace - 13:52:48] Sending request 'html/tag - (27)'.
[Trace - 13:52:48] Received response 'html/tag - (27)' in 1ms.
[Trace - 13:52:48] Sending request 'textDocument/codeAction - (28)'.
[Trace - 13:52:48] Received response 'textDocument/codeAction - (28)' in 6ms.
Using Svelte v3.48.0 from c:\Workspace\svelteTest\my-app\node_modules\svelte\compiler
Using Svelte v3.48.0 from c:\Workspace\svelteTest\my-app\node_modules\svelte\compiler
[Trace - 13:52:49] Received notification 'textDocument/publishDiagnostics'.
[Trace - 13:52:49] Sending request 'textDocument/codeAction - (29)'.
[Trace - 13:52:49] Received response 'textDocument/codeAction - (29)' in 2ms.
[Trace - 13:52:50] Received response 'textDocument/semanticTokens/full - (24)' in 3066ms.
[Trace - 13:52:50] Sending request 'textDocument/documentColor - (30)'.
[Trace - 13:52:51] Received response 'textDocument/documentColor - (30)' in 1014ms.
[Trace - 13:52:52] Sending request 'textDocument/semanticTokens/full - (31)'.
[Trace - 13:52:52] Sending request 'textDocument/documentSymbol - (32)'.
[Trace - 13:52:53] Received response 'textDocument/semanticTokens/full - (31)' in 1011ms.
[Trace - 13:52:53] Received response 'textDocument/documentSymbol - (32)' in 1022ms.
```

**Comment by jasonlyu123** [comment]
That "skipping" log is expected and unrelated to OP's problem. We now hide the parser error if you didn't properly set up a `svelte.config.js` and we detect a lang attribute.

You can follow the [docs](https://github.com/sveltejs/language-tools/blob/master/docs/preprocessors/in-general.md) to set up a svelte.config.js. 

What do you mean by "intelligence"? It's just the diagnostics? Or there are other features not working?

**Comment by falco467** [comment]
> That "skipping" log is expected and unrelated to OP's problem. We now hide the parser error if you didn't properly set up a `svelte.config.js` and we detect a lang attribute. You can follow the [docs](https://github.com/sveltejs/language-tools/blob/master/docs/preprocessors/in-general.md) to set up a svelte.config.js.
> 
> What do you mean by intellisense? It's just the diagnostics? Or there are other features not working?

Hi! The interesting thing is - this "skipping" error only appears with the newer version, not with the old version, when I perform the exact same change on the same file.

What stops working: Syntax highlighting seems to freeze, the colors do no longer match the word boundaries, code errors are also reported at the wrong position, even when fixed. It seems that everything related to parsing the code freezes at a certain state of the file and new changes are completely ignored.
As soon as I restart the language server everything is working again and the wrong errors/highlighting are again in sync, but only for a few seconds.

<img width="385" alt="image" src="https://user-images.githubusercontent.com/11572535/189124020-cb54442c-e046-4a55-a708-8c9a33aee7b5.png">

**Comment by falco467** [comment]
> Would be appreciated if you open another issue with a reproduction. It doesn't seem like it's just an issue of skipping.

I can create a guide to reproduce the issue, but as far as I can see I have exactly the same issue as the OP, so I don't think opening a same issue as a duplicate for the same bug would be helpful.

**Comment by jasonlyu123** [comment]
Is it only happen in some specific files? I did see something similar a while ago but never reliably reproduce it.

**Comment by falco467** [comment]
After several tests I think the problem is caused by an older svelte version in combination with the new extension version. I updated my NPM dependencies to the following and the problem is gone:

```
"svelte": "^3.49.0",
"@sveltejs/vite-plugin-svelte": "^1.0.2",
```

@ShapeMess and @JoDo-dev can you try and reproduce with the newest npm library versions?

**Comment by jasonlyu123** [comment]
I suspect this is the same issue as #1627, or at least some of the commenters. The issue has something to do with VSCode using a file path that differs in the casing from the one in the file system. It usually happens because you renamed the file with a different casing and VSCode caches it. In that case, close all the tabs in your editor and restart the editor should fix it. If the file is committed to git already, you can try git mv to rename the casing.

The file path casing issue would still be tracked in #1627. Since it got a clear reproduction. If any of you want to track the progress with it you can subscribe to that thread instead.

**Comment by jaymakes11** [comment]
On a related note, I found that linting was not working at all until adding the following to my user JSON settings file:

```json
"eslint.validate": [
	"svelte"
]
```

Perhaps this helps someone.

**Comment by jasonlyu123** [comment]
@ShapeMess Does this issue still pop up after we fix #1627? If not I am going to close this as resolved.

**Comment by ShapeMess** [comment]
@jasonlyu123 Can't really tell. I had reinstalled my entire OS since I last had this issue and it had not reappeared so far.
So considering this I can't really test those things out as it was happening specifically on my main PC with the previous Windows installation.

**Comment by jasonlyu123** [comment]
I am closing this since you can't reproduce it anymore, and the suspect cause is fixed. If it happens again, we can reopen this.

**Comment by YTFGolf** [comment]
I am unsure if I should be responding to this thread after a year and a half but it seems my problem is the same as the original one presented here.

I'm getting the same issue with v108.5.2. After about 5 seconds, the language server stops updating, so if it finds an error once it starts loading then it will just permanently show an error even if I fix it. The only way to fix the highlighting is to restart the server.

I fixed it by downgrading to v108.5.1, but I don't know what caused the error and it would be good if it was fixed in future versions.

**Comment by jasonlyu123** [comment]
@YTFGolf  Does this happen to all the files or on a specific file? If it's a particular file, Can you recall if you have renamed the casing of a file? For example, Test.svelte to test.svelte. Or if the casing on the tab/file explorer or VSCode differs from the one in the file system? Please reply to #2419. This shouldn't be related to the original issue since 108.5.1 doesn't have the problem.

**Comment by ahmedsat** [comment]
this is happening  for me to
`[Trace - 11:12:43 AM] Sending notification 'workspace/didChangeWatchedFiles'.
[Trace - 11:12:44 AM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 11:12:44 AM] Received request 'workspace/inlayHint/refresh - (5)'.
[Trace - 11:12:44 AM] Sending response 'workspace/inlayHint/refresh - (5)'. Processing request took 0ms
[Trace - 11:12:44 AM] Received request 'workspace/semanticTokens/refresh - (6)'.
[Trace - 11:12:44 AM] Sending response 'workspace/semanticTokens/refresh - (6)'. Processing request took 0ms
[Trace - 11:13:14 AM] Sending request 'textDocument/documentColor - (46)'.
[Trace - 11:13:14 AM] Sending request 'textDocument/codeAction - (47)'.
[Trace - 11:13:14 AM] Received response 'textDocument/codeAction - (47)' in 2ms.
[Trace - 11:13:14 AM] Sending request 'textDocument/inlayHint - (48)'.
[Trace - 11:13:14 AM] Received response 'textDocument/inlayHint - (48)' in 1ms.
[Trace - 11:13:15 AM] Sending request 'textDocument/codeAction - (49)'.
[Trace - 11:13:15 AM] Sending request 'textDocument/semanticTokens/full - (50)'.
[Trace - 11:13:15 AM] Sending request 'textDocument/documentSymbol - (51)'.
[Trace - 11:13:15 AM] Sending request 'textDocument/foldingRange - (52)'.
[Trace - 11:13:15 AM] Received response 'textDocument/codeAction - (49)' in 6ms.
[Trace - 11:13:15 AM] Received response 'textDocument/semanticTokens/full - (50)' in 8ms.
[Trace - 11:13:15 AM] Received response 'textDocument/foldingRange - (52)' in 7ms.
[Trace - 11:13:15 AM] Sending request 'textDocument/hover - (53)'.
[Trace - 11:13:15 AM] Received response 'textDocument/hover - (53)' in 36ms.
[Trace - 11:13:15 AM] Sending request 'textDocument/hover - (54)'.
[Trace - 11:13:15 AM] Received response 'textDocument/hover - (54)' in 3ms.
[Trace - 11:13:15 AM] Sending request 'textDocument/codeAction - (55)'.
[Trace - 11:13:15 AM] Received response 'textDocument/codeAction - (55)' in 5ms.
[Trace - 11:13:15 AM] Received response 'textDocument/documentColor - (46)' in 1006ms.
[Trace - 11:13:16 AM] Received response 'textDocument/documentSymbol - (51)' in 1004ms.
[Trace - 11:13:21 AM] Sending notification 'textDocument/didChange'.
[Trace - 11:13:21 AM] Sending request 'textDocument/signatureHelp - (56)'.
SnapshotManager File Statistics:
Project files: 3
Svelte files: 1
From node_modules: 144
Total: 148
[Trace - 11:13:21 AM] Received response 'textDocument/signatureHelp - (56)' in 32ms.
[Trace - 11:13:21 AM] Sending request 'textDocument/semanticTokens/full - (57)'.
[Trace - 11:13:21 AM] Received response 'textDocument/semanticTokens/full - (57)' in 1ms.
[Trace - 11:13:21 AM] Sending request 'textDocument/foldingRange - (58)'.
[Trace - 11:13:21 AM] Received response 'textDocument/foldingRange - (58)' in 12ms.
[Trace - 11:13:21 AM] Sending request 'textDocument/documentSymbol - (59)'.
[Trace - 11:13:21 AM] Sending request 'textDocument/codeAction - (60)'.
[Trace - 11:13:22 AM] Received response 'textDocument/codeAction - (60)' in 174ms.
[Trace - 11:13:22 AM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 11:13:22 AM] Sending request 'textDocument/codeAction - (61)'.
[Trace - 11:13:22 AM] Received response 'textDocument/codeAction - (61)' in 5ms.
[Trace - 11:13:22 AM] Sending request 'textDocument/documentColor - (62)'.
[Trace - 11:13:22 AM] Sending request 'textDocument/documentSymbol - (63)'.
[Trace - 11:13:22 AM] Sending request 'textDocument/inlayHint - (64)'.
[Trace - 11:13:22 AM] Received response 'textDocument/inlayHint - (64)' in 1ms.
[Trace - 11:13:22 AM] Received response 'textDocument/documentSymbol - (59)' in 1002ms.
[Trace - 11:13:22 AM] Sending notification 'textDocument/didChange'.
[Trace - 11:13:22 AM] Sending request 'textDocument/completion - (65)'.
[Trace - 11:13:22 AM] Received response 'textDocument/completion - (65)' in 18ms.
[Trace - 11:13:22 AM] Sending request 'completionItem/resolve - (66)'.
[Trace - 11:13:22 AM] Received response 'completionItem/resolve - (66)' in 2ms.
[Trace - 11:13:23 AM] Sending notification 'textDocument/didChange'.
[Trace - 11:13:23 AM] Sending request 'textDocument/semanticTokens/full - (67)'.
[Trace - 11:13:23 AM] Received response 'textDocument/semanticTokens/full - (67)' in 30ms.
[Trace - 11:13:23 AM] Sending request 'textDocument/foldingRange - (68)'.
[Trace - 11:13:23 AM] Received response 'textDocument/foldingRange - (68)' in 3ms.
[Trace - 11:13:23 AM] Sending request 'textDocument/documentSymbol - (69)'.
[Trace - 11:13:23 AM] Sending request 'textDocument/codeAction - (70)'.
[Trace - 11:13:23 AM] Received response 'textDocument/codeAction - (70)' in 70ms.
[Trace - 11:13:23 AM] Received response 'textDocument/documentSymbol - (63)' in 1003ms.
[Trace - 11:13:23 AM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 11:13:23 AM] Sending notification 'textDocument/didChange'.
[Trace - 11:13:23 AM] Sending notification '$/cancelRequest'.
[Trace - 11:13:23 AM] Sending request 'textDocument/documentColor - (71)'.
[Trace - 11:13:24 AM] Sending request 'textDocument/foldingRange - (72)'.
[Trace - 11:13:24 AM] Received response 'textDocument/foldingRange - (72)' in 10ms.
[Trace - 11:13:24 AM] Sending request 'textDocument/semanticTokens/full - (73)'.
[Trace - 11:13:24 AM] Received response 'textDocument/semanticTokens/full - (73)' in 12ms.
[Trace - 11:13:24 AM] Sending request 'textDocument/documentSymbol - (74)'.
[Trace - 11:13:24 AM] Sending request 'textDocument/codeAction - (75)'.
[Trace - 11:13:24 AM] Received response 'textDocument/codeAction - (75)' in 133ms.
[Trace - 11:13:24 AM] Received response 'textDocument/documentSymbol - (69)' in 1002ms.
[Trace - 11:13:24 AM] Sending notification 'textDocument/didChange'.
[Trace - 11:13:24 AM] Sending notification '$/cancelRequest'.
[Trace - 11:13:24 AM] Sending request 'textDocument/foldingRange - (76)'.
[Trace - 11:13:24 AM] Received response 'textDocument/foldingRange - (76)' in 10ms.
[Trace - 11:13:24 AM] Sending request 'textDocument/semanticTokens/full - (77)'.
[Trace - 11:13:24 AM] Received response 'textDocument/semanticTokens/full - (77)' in 23ms.
[Trace - 11:13:24 AM] Sending request 'textDocument/documentSymbol - (78)'.
[Trace - 11:13:24 AM] Sending request 'textDocument/codeAction - (79)'.
[Trace - 11:13:24 AM] Received response 'textDocument/codeAction - (79)' in 123ms.
[Trace - 11:13:24 AM] Received response 'textDocument/documentColor - (71)' in 1002ms.
[Trace - 11:13:25 AM] Sending request 'textDocument/completion - (80)'.
[Trace - 11:13:25 AM] Received response 'textDocument/completion - (80)' in 8ms.
[Trace - 11:13:25 AM] Sending request 'completionItem/resolve - (81)'.
[Trace - 11:13:25 AM] Received response 'completionItem/resolve - (81)' in 8ms.
[Trace - 11:13:25 AM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 11:13:25 AM] Received response 'textDocument/documentSymbol - (74)' in 1001ms.
[Trace - 11:13:25 AM] Sending request 'textDocument/codeAction - (82)'.
[Trace - 11:13:25 AM] Received response 'textDocument/codeAction - (82)' in 4ms.
[Trace - 11:13:25 AM] Sending request 'textDocument/documentColor - (83)'.
[Trace - 11:13:25 AM] Sending request 'textDocument/documentSymbol - (84)'.
[Trace - 11:13:25 AM] Received response 'textDocument/documentColor - (62)' in 3003ms.
[Trace - 11:13:25 AM] Sending request 'textDocument/inlayHint - (85)'.
[Trace - 11:13:25 AM] Received response 'textDocument/inlayHint - (85)' in 2ms.
[Trace - 11:13:25 AM] Received response 'textDocument/documentSymbol - (78)' in 1003ms.
[Trace - 11:13:26 AM] Received response 'textDocument/documentColor - (83)' in 1002ms.
[Trace - 11:13:26 AM] Received response 'textDocument/documentSymbol - (84)' in 1003ms.
[Trace - 11:13:28 AM] Sending notification 'textDocument/didChange'.
[Trace - 11:13:28 AM] Sending request 'completionItem/resolve - (86)'.
[Trace - 11:13:28 AM] Received response 'completionItem/resolve - (86)' in 9ms.
[Trace - 11:13:28 AM] Sending request 'textDocument/foldingRange - (87)'.
[Trace - 11:13:28 AM] Received response 'textDocument/foldingRange - (87)' in 5ms.
[Trace - 11:13:29 AM] Sending request 'textDocument/semanticTokens/full - (88)'.
[Trace - 11:13:29 AM] Received response 'textDocument/semanticTokens/full - (88)' in 1ms.
[Trace - 11:13:29 AM] Sending request 'textDocument/documentSymbol - (89)'.
[Trace - 11:13:29 AM] Sending request 'textDocument/codeAction - (90)'.
[Trace - 11:13:29 AM] Received response 'textDocument/codeAction - (90)' in 107ms.
[Trace - 11:13:29 AM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 11:13:29 AM] Sending notification 'textDocument/didChange'.
[Trace - 11:13:29 AM] Sending notification '$/cancelRequest'.
[Trace - 11:13:29 AM] Sending request 'textDocument/foldingRange - (91)'.
[Trace - 11:13:29 AM] Received response 'textDocument/foldingRange - (91)' in 12ms.
[Trace - 11:13:30 AM] Sending request 'textDocument/semanticTokens/full - (92)'.
[Trace - 11:13:30 AM] Received response 'textDocument/semanticTokens/full - (92)' in 25ms.
[Trace - 11:13:30 AM] Sending request 'textDocument/documentSymbol - (93)'.
[Trace - 11:13:30 AM] Sending request 'textDocument/codeAction - (94)'.
[Trace - 11:13:30 AM] Sending request 'textDocument/documentColor - (95)'.
[Trace - 11:13:30 AM] Received response 'textDocument/codeAction - (94)' in 61ms.
[Trace - 11:13:30 AM] Received response 'textDocument/documentSymbol - (89)' in 1006ms.
[Trace - 11:13:30 AM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 11:13:30 AM] Sending notification 'textDocument/didChange'.
[Trace - 11:13:30 AM] Sending notification '$/cancelRequest'.
[Trace - 11:13:30 AM] Sending request 'textDocument/foldingRange - (96)'.
[Trace - 11:13:30 AM] Received response 'textDocument/foldingRange - (96)' in 8ms.
[Trace - 11:13:30 AM] Sending request 'textDocument/semanticTokens/full - (97)'.
[Trace - 11:13:30 AM] Received response 'textDocument/semanticTokens/full - (97)' in 8ms.
[Trace - 11:13:31 AM] Sending request 'textDocument/documentSymbol - (98)'.
[Trace - 11:13:31 AM] Received response 'textDocument/documentSymbol - (93)' in 1001ms.
[Trace - 11:13:31 AM] Sending request 'textDocument/codeAction - (99)'.
[Trace - 11:13:31 AM] Received response 'textDocument/codeAction - (99)' in 61ms.
[Trace - 11:13:31 AM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 11:13:31 AM] Sending request 'textDocument/codeAction - (100)'.
[Trace - 11:13:31 AM] Received response 'textDocument/codeAction - (100)' in 4ms.
[Trace - 11:13:31 AM] Sending notification 'textDocument/didChange'.
[Trace - 11:13:31 AM] Sending notification '$/cancelRequest'.
[Trace - 11:13:32 AM] Sending request 'textDocument/foldingRange - (101)'.
[Trace - 11:13:32 AM] Received response 'textDocument/foldingRange - (101)' in 8ms.
[Trace - 11:13:32 AM] Sending request 'textDocument/documentColor - (102)'.
[Trace - 11:13:32 AM] Received response 'textDocument/documentSymbol - (98)' in 1001ms.
[Trace - 11:13:32 AM] Sending request 'textDocument/semanticTokens/full - (103)'.
[Trace - 11:13:32 AM] Received response 'textDocument/semanticTokens/full - (103)' in 8ms.
[Trace - 11:13:32 AM] Sending request 'textDocument/codeAction - (104)'.
[Trace - 11:13:32 AM] Sending request 'textDocument/documentSymbol - (105)'.
[Trace - 11:13:32 AM] Received response 'textDocument/codeAction - (104)' in 54ms.
[Trace - 11:13:32 AM] Received response 'textDocument/documentColor - (95)' in 2077ms.
[Trace - 11:13:32 AM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 11:13:32 AM] Sending request 'textDocument/codeAction - (106)'.
[Trace - 11:13:32 AM] Received response 'textDocument/codeAction - (106)' in 4ms.
[Trace - 11:13:32 AM] Sending request 'textDocument/documentSymbol - (107)'.
[Trace - 11:13:32 AM] Sending notification 'textDocument/didChange'.
[Trace - 11:13:33 AM] Sending notification '$/cancelRequest'.
[Trace - 11:13:33 AM] Sending request 'textDocument/foldingRange - (108)'.
[Trace - 11:13:33 AM] Received response 'textDocument/foldingRange - (108)' in 8ms.
[Trace - 11:13:33 AM] Received response 'textDocument/documentSymbol - (105)' in 1027ms.
[Trace - 11:13:33 AM] Sending request 'textDocument/semanticTokens/full - (109)'.
[Trace - 11:13:33 AM] Received response 'textDocument/semanticTokens/full - (109)' in 8ms.
[Trace - 11:13:33 AM] Sending request 'textDocument/documentSymbol - (110)'.
[Trace - 11:13:33 AM] Sending request 'textDocument/codeAction - (111)'.
[Trace - 11:13:33 AM] Received response 'textDocument/codeAction - (111)' in 58ms.
[Trace - 11:13:33 AM] Sending notification 'textDocument/didChange'.
[Trace - 11:13:33 AM] Sending notification '$/cancelRequest'.
[Trace - 11:13:33 AM] Sending request 'textDocument/foldingRange - (112)'.
[Trace - 11:13:33 AM] Sending request 'textDocument/codeAction - (113)'.
[Trace - 11:13:33 AM] Received response 'textDocument/foldingRange - (112)' in 4ms.
[Trace - 11:13:33 AM] Sending request 'textDocument/semanticTokens/full - (114)'.
[Trace - 11:13:33 AM] Received response 'textDocument/codeAction - (113)' in 85ms.
[Trace - 11:13:33 AM] Received response 'textDocument/semanticTokens/full - (114)' in 48ms.
[Trace - 11:13:33 AM] Sending request 'textDocument/documentSymbol - (115)'.
[Trace - 11:13:33 AM] Received response 'textDocument/documentSymbol - (107)' in 1001ms.
[Trace - 11:13:34 AM] Sending request 'textDocument/codeAction - (116)'.
[Trace - 11:13:34 AM] Received response 'textDocument/codeAction - (116)' in 4ms.
[Trace - 11:13:34 AM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 11:13:34 AM] Received response 'textDocument/documentSymbol - (110)' in 1001ms.
[Trace - 11:13:34 AM] Sending request 'textDocument/documentColor - (117)'.
[Trace - 11:13:34 AM] Sending request 'textDocument/codeAction - (118)'.
[Trace - 11:13:34 AM] Received response 'textDocument/codeAction - (118)' in 4ms.
[Trace - 11:13:34 AM] Sending request 'textDocument/documentSymbol - (119)'.
[Trace - 11:13:34 AM] Sending request 'textDocument/inlayHint - (120)'.
[Trace - 11:13:34 AM] Received response 'textDocument/inlayHint - (120)' in 2ms.
[Trace - 11:13:34 AM] Received response 'textDocument/documentSymbol - (115)' in 1002ms.
[Trace - 11:13:35 AM] Received response 'textDocument/documentColor - (102)' in 3001ms.
[Trace - 11:13:35 AM] Sending request 'textDocument/codeAction - (121)'.
[Trace - 11:13:35 AM] Received response 'textDocument/codeAction - (121)' in 2ms.
[Trace - 11:13:35 AM] Received response 'textDocument/documentColor - (117)' in 1002ms.
[Trace - 11:13:35 AM] Received response 'textDocument/documentSymbol - (119)' in 1003ms.
[Trace - 11:13:36 AM] Sending request 'textDocument/formatting - (122)'.
[Trace - 11:13:36 AM] Received response 'textDocument/formatting - (122)' in 22ms.
[Trace - 11:13:36 AM] Sending notification 'textDocument/didChange'.
[Trace - 11:13:36 AM] Sending notification 'textDocument/didSave'.
[Trace - 11:13:36 AM] Sending request 'textDocument/foldingRange - (123)'.
[Trace - 11:13:36 AM] Received response 'textDocument/foldingRange - (123)' in 4ms.
[Trace - 11:13:36 AM] Sending request 'textDocument/semanticTokens/full - (124)'.
[Trace - 11:13:36 AM] Received response 'textDocument/semanticTokens/full - (124)' in 14ms.
[Trace - 11:13:36 AM] Sending notification 'workspace/didChangeWatchedFiles'.
[Trace - 11:13:36 AM] Sending request 'textDocument/documentSymbol - (125)'.
[Trace - 11:13:36 AM] Sending request 'textDocument/codeAction - (126)'.
[Trace - 11:13:36 AM] Received response 'textDocument/codeAction - (126)' in 7ms.
[Trace - 11:13:37 AM] Sending request 'textDocument/documentSymbol - (127)'.
[Trace - 11:13:37 AM] Sending request 'textDocument/inlayHint - (128)'.
[Trace - 11:13:37 AM] Received response 'textDocument/inlayHint - (128)' in 1ms.
[Trace - 11:13:37 AM] Received response 'textDocument/documentSymbol - (125)' in 1008ms.
[Trace - 11:13:37 AM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 11:13:37 AM] Sending request 'textDocument/codeAction - (129)'.
[Trace - 11:13:37 AM] Received response 'textDocument/codeAction - (129)' in 2ms.
[Trace - 11:13:37 AM] Received request 'workspace/inlayHint/refresh - (7)'.
[Trace - 11:13:37 AM] Sending response 'workspace/inlayHint/refresh - (7)'. Processing request took 1ms
[Trace - 11:13:37 AM] Sending request 'textDocument/documentColor - (130)'.
[Trace - 11:13:37 AM] Received request 'workspace/semanticTokens/refresh - (8)'.
[Trace - 11:13:37 AM] Sending response 'workspace/semanticTokens/refresh - (8)'. Processing request took 1ms
[Trace - 11:13:37 AM] Sending request 'textDocument/semanticTokens/full - (131)'.
[Trace - 11:13:37 AM] Received response 'textDocument/semanticTokens/full - (131)' in 2ms.
[Trace - 11:13:37 AM] Sending request 'textDocument/inlayHint - (132)'.
[Trace - 11:13:37 AM] Received response 'textDocument/inlayHint - (132)' in 1ms.
[Trace - 11:13:38 AM] Received response 'textDocument/documentSymbol - (127)' in 1004ms.
[Trace - 11:13:38 AM] Received response 'textDocument/documentColor - (130)' in 1002ms.
`

**Comment by ahmedsat** [comment]
> Please ensure to update to the latest version of the VS Code extension

i have update the plugin tho latest problem is the same the only way i found is to run "svelte.restartLanguageServer"

**Comment by dummdidumm** [comment]
In that case please open a new issue with a proper reproduction
